name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12"]
        compiler: ["gcc", "clang"]
    runs-on: ${{matrix.os}}

      #- if: ${{ matrix.os == 'ubuntu-22.04' && matrix.compiler == 'gcc'}}
      #  env:
      #    OMPI_CXX = 'g++'
      #- if: ${{ matrix.os == 'ubuntu-22.04' && matrix.compiler == 'clang'}}
      #  env:
      #    OMPI_CXX = 'clang++'
      #- if: ${{ matrix.os == 'macos-12' && matrix.compiler == 'clang'}}
      #  env:
      #    OMPI_CXX = 'clang++'
      #- if: ${{ matrix.os == 'macos-12' && matrix.compiler == 'gcc'}}
      #  env:
      #    OMPI_CXX = 'g++-12'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: ${{matrix.os == "ubuntu-22.04"}}
        name: Install mpi
        run: sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev libnetcdf-dev
      
      - if: ${{matrix.os == "macos-12"}}
        name: Install mpi
        run: brew install open-mpi netcdf

      - name: Configure and build
        run: |
          source ./machines/ubuntu.sh &&
          cd build &&
          ./cmakescript.sh &&
          cmake --build .
      - name: Test
        working-directory: ${{github.workspace}}/build
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}

